## Wind Production

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../raw_data/productionconsumptionsettlement.csv")
data.head()

,ExchangeGE_MWh,HourUTC,TransmissionLossMWh,OffshoreWindLt100MW_MWh,PowerToHeatMWh,OnshoreWindLt50kW_MWh,ExchangeNO_MWh,CentralPowerMWh,SolarPowerGe10Lt40kW_MWh,OffshoreWindGe100MW_MWh,...,SolarPowerSelfConMWh,ExchangeNL_MWh,LocalPowerMWh,HourDK,PriceArea,LocalPowerSelfConMWh,OnshoreWindGe50kW_MWh,GrossConsumptionMWh,ExchangeGreatBelt_MWh,SolarPowerLt10kW_MWh
0,570.60,2020-11-18T22:00:00,-29.9550,69.241621,287.448717,17.027991,-659.564,129.17251,0.002987,917.908635,...,0.170894,-0.63,181.482178,2020-11-18T23:00:00,DK1,0.060375,1726.722800,2362.123374,-591.6,0.021782
1,415.30,2020-11-18T21:00:00,-26.4724,69.311505,232.284072,17.031704,-543.732,138.06312,0.003785,979.052898,...,-0.055510,-0.60,206.600711,2020-11-18T22:00:00,DK1,0.060659,1937.467487,2628.465603,-591.6,0.022378
2,421.19,2020-11-18T20:00:00,-17.4066,69.153656,236.172386,16.558283,-203.944,107.97530,0.003258,909.795043,...,-0.049935,-0.60,216.592558,2020-11-18T21:00:00,DK1,0.057240,1879.142855,2825.747594,-591.7,0.022254
3,367.22,2020-11-18T19:00:00,-15.4531,86.723072,230.586103,16.364780,18.040,148.20276,0.003067,891.065528,...,-0.058530,-0.60,202.468927,2020-11-18T20:00:00,DK1,0.054376,1889.218317,3028.706290,-591.6,0.028261
4,305.49,2020-11-18T18:00:00,-12.0949,86.300697,155.940747,16.108948,114.376,154.82271,0.001930,888.092495,...,-0.054135,-0.60,201.690080,2020-11-18T19:00:00,DK1,0.053685,1991.504240,3167.828975,-591.6,0.024941

In [3]:
measures = data.drop(columns=["HourUTC","HourDK"]).columns # actual prod values

df = data[["HourDK"] + list(measures)]
df['time'] = pd.to_datetime(df['HourDK'].replace("T", " "))

In [4]:
df = df.drop(columns="HourDK").sort_values(by="time").set_index("time").loc["2015-01-01":]

In [5]:
df.head()

,ExchangeGE_MWh,TransmissionLossMWh,OffshoreWindLt100MW_MWh,PowerToHeatMWh,OnshoreWindLt50kW_MWh,ExchangeNO_MWh,CentralPowerMWh,SolarPowerGe10Lt40kW_MWh,OffshoreWindGe100MW_MWh,ExchangeSE_MWh,...,HydroPowerMWh,SolarPowerSelfConMWh,ExchangeNL_MWh,LocalPowerMWh,PriceArea,LocalPowerSelfConMWh,OnshoreWindGe50kW_MWh,GrossConsumptionMWh,ExchangeGreatBelt_MWh,SolarPowerLt10kW_MWh
time,,,,,,,,,,,,,,,,,,,,,
2015-01-01 00:00:00,703.3,-121.0,42.329932,11.3,36.037823,-1137.6,788.3,0.0,633.42260,-348.8,...,1.737465,NaN,NaN,255.957172,DK1,0.0,1195.531801,1909.816793,-260.4,NaN
2015-01-01 01:00:00,684.3,-82.0,36.938565,11.3,0.939794,-1453.9,844.0,0.0,591.55785,-326.8,...,1.722133,NaN,NaN,249.236984,DK1,0.0,1202.936083,1836.231409,5.3,NaN
2015-01-01 02:00:00,681.4,-98.0,37.788579,11.6,0.953450,-1538.2,743.8,0.0,528.97895,-318.4,...,1.723660,NaN,NaN,248.662031,DK1,0.0,1199.156501,1763.263171,177.4,NaN
2015-01-01 03:00:00,817.1,-106.0,42.000662,11.8,1.069252,-1529.4,622.8,0.0,507.72750,-316.4,...,1.720773,NaN,NaN,234.131074,DK1,0.0,1335.010455,1689.959716,-25.8,NaN
2015-01-01 04:00:00,687.9,-107.0,45.700564,16.6,1.307552,-1603.4,481.2,0.0,614.14425,-299.2,...,1.726118,NaN,NaN,227.850461,DK1,0.0,1472.801627,1659.530572,29.5,NaN

### Feature Engineering

In [6]:
wind = ["OffshoreWindLt100MW_MWh","OffshoreWindGe100MW_MWh","OnshoreWindLt50kW_MWh",
                "OnshoreWindGe50kW_MWh"]

non_wind = ["CentralPowerMWh","LocalPowerMWh","HydroPowerMWh","SolarPowerLt10kW_MWh",
            "SolarPowerGe10Lt40kW_MWh","SolarPowerGe40kW_MWh","TransmissionLossMWh"]

irrelevant_cols = ["PriceArea","ExchangeGE_MWh","PowerToHeatMWh","ExchangeNO_MWh","ExchangeSE_MWh",
                "ExchangeNL_MWh","GrossConsumptionMWh","ExchangeGreatBelt_MWh","LocalPowerSelfConMWh"]

substract_cols = "SolarPowerSelfConMWh"

In [7]:
df = df.drop(columns=irrelevant_cols)
df[substract_cols] = df[substract_cols].fillna(0)

part_null_cols = ["SolarPowerGe10Lt40kW_MWh","SolarPowerGe40kW_MWh","SolarPowerLt10kW_MWh","TransmissionLossMWh"] 
df[part_null_cols] = df[part_null_cols].fillna(0)

In [8]:
df.isna().sum()

TransmissionLossMWh         0
OffshoreWindLt100MW_MWh     0
OnshoreWindLt50kW_MWh       0
CentralPowerMWh             0
SolarPowerGe10Lt40kW_MWh    0
OffshoreWindGe100MW_MWh     0
SolarPowerGe40kW_MWh        0
HydroPowerMWh               0
SolarPowerSelfConMWh        0
LocalPowerMWh               0
OnshoreWindGe50kW_MWh       0
SolarPowerLt10kW_MWh        0
dtype: int64

In [9]:
df['wind_prod'] = df[wind].sum(axis=1)

In [12]:
df["non_wind_prod"] = df[non_wind].sum(axis=1)

In [13]:
df["total_prod"] = df["wind_prod"] + df["non_wind_prod"] - df[substract_cols]
df["wind_share"] = df["wind_prod"]/df["total_prod"]

In [14]:
final_df = df[["wind_prod", "non_wind_prod", "total_prod", "wind_share"]]

### Put into a function

In [15]:
def get_wind_prod(path="../raw_data/productionconsumptionsettlement.csv"):
    """Returns a feature-engineered dataframe including:
    1. Wind production
    2. Non-wind production
    3. Total production
    4. Wind share of total production
    """
    data = pd.read_csv(path)
    
    # columns with actual (needed) prod values
    measures = data.drop(columns=["HourUTC","HourDK"]).columns 
    df = data[["HourDK"] + list(measures)]
    
    # convert to datetime and set time index
    df['time'] = pd.to_datetime(df['HourDK'].replace("T", " "))
    df = df.drop(columns="HourDK").sort_values(by="time").set_index("time").loc["2015-01-01":]
    
    # columns to be engineered
    wind = ["OffshoreWindLt100MW_MWh", "OffshoreWindGe100MW_MWh",
            "OnshoreWindLt50kW_MWh", "OnshoreWindGe50kW_MWh"]

    non_wind = ["CentralPowerMWh", "LocalPowerMWh", "HydroPowerMWh",
                "SolarPowerLt10kW_MWh", "SolarPowerGe10Lt40kW_MWh",
                "SolarPowerGe40kW_MWh", "TransmissionLossMWh"]

    irrelevant_cols = ["PriceArea","ExchangeGE_MWh","PowerToHeatMWh",
                       "ExchangeNO_MWh","ExchangeSE_MWh", "ExchangeNL_MWh",
                       "GrossConsumptionMWh","ExchangeGreatBelt_MWh",
                       "LocalPowerSelfConMWh"]

    substract_cols = "SolarPowerSelfConMWh"
    
    part_null_cols = ["SolarPowerGe10Lt40kW_MWh","SolarPowerGe40kW_MWh",
                      "SolarPowerLt10kW_MWh","TransmissionLossMWh"]
    
    # drop irrelevant
    df = df.drop(columns=irrelevant_cols)
    # deal with NaNs
    df[substract_cols] = df[substract_cols].fillna(0)
    df[part_null_cols] = df[part_null_cols].fillna(0)
    
    # wind_prod & non_wind engineered from sum off all wind / nonwind cols
    df['wind_prod'] = df[wind].sum(axis=1)
    df["non_wind_prod"] = df[non_wind].sum(axis=1)
    
    # total prod and wind percentage of total defined
    df["total_prod"] = df["wind_prod"] + df["non_wind_prod"] - df[substract_cols]
    df["wind_share"] = df["wind_prod"] / df["total_prod"]
    
    # final df with engineered cols
    final_df = df[["wind_prod", "non_wind_prod", "total_prod", "wind_share"]]
    
    return final_df

In [16]:
get_wind_prod()

                       wind_prod  non_wind_prod   total_prod  wind_share
time
2015-01-01 00:00:00  1907.322156     924.994637  2832.316793    0.673414
2015-01-01 01:00:00  1832.372292    1012.959117  2845.331409    0.643993
2015-01-01 02:00:00  1766.877480     896.185691  2663.063171    0.663476
2015-01-01 03:00:00  1885.807869     752.651847  2638.459716    0.714738
2015-01-01 04:00:00  2133.953993     603.776579  2737.730572    0.779461
...                          ...            ...          ...         ...
2020-11-18 19:00:00  2982.006380     346.062145  3328.122660    0.896003
2020-11-18 20:00:00  2883.371697     336.825647  3220.255874    0.895386
2020-11-18 21:00:00  2874.649837     308.737852  3183.437624    0.903002
2020-11-18 22:00:00  3002.863594     319.756460  3322.675564    0.903749
2020-11-18 23:00:00  2730.901047     282.230058  3012.960211    0.906385

[51576 rows x 4 columns]

### Test from module

In [1]:
from electricity_price_predictor.data import get_wind_prod

In [2]:
get_wind_prod()

                       wind_prod  wind_share
time
2015-01-01 00:00:00  1907.322156    0.673414
2015-01-01 01:00:00  1832.372292    0.643993
2015-01-01 02:00:00  1766.877480    0.663476
2015-01-01 03:00:00  1885.807869    0.714738
2015-01-01 04:00:00  2133.953993    0.779461
...                          ...         ...
2020-11-18 19:00:00  2982.006380    0.896003
2020-11-18 20:00:00  2883.371697    0.895386
2020-11-18 21:00:00  2874.649837    0.903002
2020-11-18 22:00:00  3002.863594    0.903749
2020-11-18 23:00:00  2730.901047    0.906385

[51576 rows x 2 columns]